version: '3.9'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: versanetbd
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./versanetbd.sql:/docker-entrypoint-initdb.d/init.sql
  backend:
    build: ./Backend
    container_name: node_backend
    restart: always
    ports:
      - "5000:5000"
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
      - MYSQL_DATABASE=versanetbd
      - MYSQL_PORT=3306
      - JWT_SECRET=mysecretkey
      - PORT=5000
      - MAIL_HOST=smtp.gmail.com
      - MAIL_PORT=465
      - MAIL_USER=yancarojas2003@gmail.com
      - MAIL_PASS=bokk vora jypi yxlh
      - MAIL_SECURE=true
      - MAIL_FROM=Versanet
    volumes:
      - .:/usr/src/app
    command: npm run dev
    depends_on:
      - mysql
  react-app:
    build:
      context: ./Frontend
      dockerfile: Dockerfile
      args:
        VITE_BASE_URL: http://localhost:5000
    ports:
      - "80:80"
    environment:
      - VITE_BASE_URL=http://localhost:5000
    depends_on:
      - backend
    restart: unless-stopped


volumes:
  mysql_data:
